name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/ml-deploy
            git pull origin main
            docker stop app || true && docker rm app || true
            docker build -t app-flask-ml .
            docker run -d -p 5000:5000 --name app-flask-ml app-flask-ml
